cookie:
  expiry_days: 1
  key: my_key
  name: my_app
credentials:
  usernames:
    admin:
      email: admin@gmail.com
      name: admin
      password: $2b$12$tjdQrgGIXKeby0p2PjAy5OBegbLx90xCA4x9vDozcWRtjz3HiQMKm
    jerrychen:
      email: jerrychen@gmail.com
      name: jerrychen
      password: $2b$12$e65t5.dm58Nb53WojrfLCO0bNINz2J7mvrF63kMYxJA41JxhaZAUi
    new_user:
      email: new_user@gmail.com
      name: new_user
      password: $2b$12$nforRh0cB9JieqZbS7tZWuluT8cs20Ila8H07Jy0d8mC2bQCjseIK
preauthorized:
  emails:
  - test@gmail.com
